org: pikimell
service: auth-service

frameworkVersion: '4'

plugins:
  - serverless-offline

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  stage: dev
  profile: serverlessUser
  timeout: 20

functions:
  # === AUTHENTICATION ===
  registerUser:
    handler: src/handlers/authHandlers.registerUserHandler
    events:
      - http:
          path: auth/register
          method: post
          cors: true

  login:
    handler: src/handlers/authHandlers.loginHandler
    events:
      - http:
          path: auth/login
          method: post
          cors: true

  logout:
    handler: src/handlers/authHandlers.logoutHandler
    events:
      - http:
          path: auth/logout
          method: post
          cors: true

  refreshToken:
    handler: src/handlers/authHandlers.refreshHandler
    events:
      - http:
          path: auth/refresh
          method: post
          cors: true

  requestResetEmail:
    handler: src/handlers/authHandlers.requestResetEmailHandler
    events:
      - http:
          path: auth/reset/request
          method: post
          cors: true

  resetPassword:
    handler: src/handlers/authHandlers.resetPasswordHandler
    events:
      - http:
          path: auth/reset/confirm
          method: post
          cors: true

  confirmEmail:
    handler: src/handlers/authHandlers.confirmEmailHandler
    events:
      - http:
          path: auth/confirm
          method: post
          cors: true

  test:
    handler: src/handlers/testHandler.testHandler
    events:
      - http:
          path: test
          method: get
          cors: true
