org: author
service: AWS-BACKEND

frameworkVersion: '4'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  stage: dev
  profile: serverlessTemplateUser
  timeout: 20

functions:
  templateGet:
    handler: src/handlers/templates/getTemplateHandler.getTemplateHandler
    events:
      - http:
          path: template
          method: get
          cors: true

  templatePost:
    handler: src/handlers/templates/createTemplateHandler.createTemplateHandler
    events:
      - http:
          path: templates
          method: post
          cors: true

  templatePut:
    handler: src/handlers/templates/putTemplateHandler.putTemplateHandler
    events:
      - http:
          path: templates/{templateId}
          method: put
          cors: true

  templateDelete:
    handler: src/handlers/templates/deleteTemplateHandler.deleteTemplateHandler
    events:
      - http:
          path: templates/{templateId}
          method: delete
          cors: true
