org: pikimell
service: auth-service

frameworkVersion: '4'

plugins:
  - serverless-offline
  - serverless-domain-manager

useDotenv: true

custom:
  customDomain:
    domainName: api.pashchenko.store
    basePath: auth
    stage: ${self:provider.stage}
    createRoute53Record: true
    certificateName: arn:aws:acm:us-east-1:884252207764:certificate/a02c8c87-b5ee-4657-aabb-8c39a95e983b

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  stage: dev
  profile: serverlessUser
  timeout: 20
  environment:
    MONGODB_USER: ${env:MONGODB_USER}
    MONGODB_PASSWORD: ${env:MONGODB_PASSWORD}
    MONGODB_URL: ${env:MONGODB_URL}
    MONGODB_DB: ${env:MONGODB_DB}
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
    COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}

functions:
  # === AUTHENTICATION ===
  registerUser:
    handler: src/handlers/authHandlers.registerUserHandler
    events:
      - http:
          path: register
          method: post
          cors: true

  login:
    handler: src/handlers/authHandlers.loginHandler
    events:
      - http:
          path: login
          method: post
          cors: true

  logout:
    handler: src/handlers/authHandlers.logoutHandler
    events:
      - http:
          path: logout
          method: post
          cors: true

  refreshToken:
    handler: src/handlers/authHandlers.refreshHandler
    events:
      - http:
          path: refresh
          method: post
          cors: true

  requestResetEmail:
    handler: src/handlers/authHandlers.requestResetEmailHandler
    events:
      - http:
          path: reset/request
          method: post
          cors: true

  resetPassword:
    handler: src/handlers/authHandlers.resetPasswordHandler
    events:
      - http:
          path: reset/confirm
          method: post
          cors: true

  confirmEmail:
    handler: src/handlers/authHandlers.confirmEmailHandler
    events:
      - http:
          path: confirm
          method: post
          cors: true

  test:
    handler: src/handlers/testHandler.testHandler
    events:
      - http:
          path: test
          method: get
          cors: true
